import tkinter as tk
windows = tk.Tk()
windows.attributes('-alpha',1)
windows.title('Green Hackers App')
windows.iconbitmap('train.ico')
screen_width = windows.winfo_screenwidth()
screen_height = windows.winfo_screenheight()
x = int((screen_width//2)-320)
x = str(x)
y = int((screen_height//2)-240)
y = str(y)
print(('640x480+' + x + '+' + y))
windows.geometry('640x480+' + x + '+' + y)
lblUsername = tk.Label(windows,text='Username: ')
lblUsername.pack()
lblPassword = tk.Label(windows,text='Password: ')
lblPassword.pack()
windows.mainloop()